package lk.ci.int_cn_system.UI.Auth;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BoardApprovalView extends Panel {
	protected Label label_nameWithInitials;
	protected Label label_address;
	protected Label label_telephoneNo;
	protected Label label_nIC;
	protected Label label_gender;
	protected Label label_email;
	protected Label label_reqsalary;
	protected Label label_highestQualification;
	protected Label label_requestingPossition;
	protected Label label_emp_mode;
	protected Label label_region;
	protected Label label_civil_state;
	protected Label label_company;
	protected TextField textField_offed_salary;
	protected TextField textField_allwnce_1;
	protected TextField textField_allwnce_2;
	protected DateField dateField_startdte;
	protected TextField textField_designtion;
	protected TextArea otherBenefits;
	protected TextArea conditions;
	protected ComboBox combobox_emptype;
	protected TextField textField_montscunt;
	protected CheckBox checkBox_chairman;
	protected CheckBox checkBox_gmtechnical;
	protected CheckBox checkBox_cEO;
	protected CheckBox checkBox_gM;
	protected CheckBox checkBox_hRM;
	protected CheckBox checkBox_hOD;
	protected Label label_dateofbirth;
	protected ComboBox comboBox_branch;
	protected ComboBox comboBox_department;
	protected Label label_Position_Confirmation;
	protected Button button_date_cal;
	protected Button btn_search;
	protected Label viewstatus;
	protected CheckBox checkBox_director;
	protected CheckBox checkBox_mD;

	public BoardApprovalView() {
		Design.read(this);
	}
}
