package lk.ci.int_cn_system.UI.Auth;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EmpReports extends AbsoluteLayout {
	protected DateField dateField_from;
	protected DateField dateField_to;
	protected Button button_print;
	protected ComboBox comboBox_cv_no;
	protected Button button_single_print;

	public EmpReports() {
		Design.read(this);
	}
}
