package lk.ci.int_cn_system.UI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DashBoard extends AbsoluteLayout {
	protected Tree treeMain;
	protected VerticalLayout verticalLayout;
	protected Image image_dashbord;
	protected AbsoluteLayout absoluteLayoutHeader;
	protected Image imageProfile;
	protected Label labelUserName;
	protected Label labelUserBranch;
	protected MenuBar menuBar;

	public DashBoard() {
		Design.read(this);
	}
}
